/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package theaterrevenue;

import java.awt.Dimension;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.NumberFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Tamu Fahnbulleh
 */
public class TheaterRevenueGUI extends javax.swing.JFrame {

    /**
     * Creates new form TheaterRevenueGUI
     */
    
    private final int MAXHEIGHT=620; //maximium height of the frame
    private final int MAXWIDTH=658; //maximium width of the frame
    private double adultTicketPrice; //store price for adult ticket
    private double childTicketPrice; //store price for child ticket
    private  Tickets adult; //instance of Ticket
    private Tickets child; //instance of ticket
    public TheaterRevenueGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        childrenTicketSoldTxtBox = new javax.swing.JTextField();
        adultTicketSoldTxtBox = new javax.swing.JTextField();
        calculateRevenueBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        childTicketPriceTxtBox = new javax.swing.JTextField();
        adultTicketPriceTxtBox = new javax.swing.JTextField();
        AboutBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTxtBox = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        childrenTicketSoldTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                childrenTicketSoldTxtBoxActionPerformed(evt);
            }
        });

        calculateRevenueBtn.setBackground(new java.awt.Color(0, 0, 255));
        calculateRevenueBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        calculateRevenueBtn.setForeground(new java.awt.Color(255, 255, 255));
        calculateRevenueBtn.setText("Calculate Revenue");
        calculateRevenueBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calculateRevenueBtnMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Price per child ticket:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Price per adult ticket:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Number of children's ticket sold:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Number of adult's ticket sold:");

        AboutBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AboutBtn.setText("About");
        AboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(childTicketPriceTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adultTicketPriceTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(childrenTicketSoldTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(adultTicketSoldTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(calculateRevenueBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(AboutBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(AboutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(childTicketPriceTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(childrenTicketSoldTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(adultTicketSoldTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(adultTicketPriceTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(37, 37, 37)
                .addComponent(calculateRevenueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        resultTxtBox.setColumns(20);
        resultTxtBox.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        resultTxtBox.setRows(5);
        jScrollPane1.setViewportView(resultTxtBox);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void childrenTicketSoldTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_childrenTicketSoldTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_childrenTicketSoldTxtBoxActionPerformed

    private void calculateRevenueBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculateRevenueBtnMouseClicked
      
       
        try
        {
             //variable assignment.
            //get the text of adultTicketSoldTxtBox and convert it to int 
            int adultTicketSold=Integer.parseInt(adultTicketSoldTxtBox.getText()); 
            
             //variable assignment.
            //get the text of childrenTicketSoldTxtBox and convert it to int 
            int childTicketSold=Integer.parseInt(childrenTicketSoldTxtBox.getText());
            
              //variable assignment.
              //get the text of adultTicketPriceTxtBox and convert it to double 
            adultTicketPrice=Double.valueOf(adultTicketPriceTxtBox.getText());
            
             //get the text of childTicketPriceTxtBox and convert it to double 
            childTicketPrice=Double.valueOf(childTicketPriceTxtBox.getText());
            
            //create new object of Ticket
            adult=new Tickets(adultTicketPrice,adultTicketSold);
            
            //crete new object of Tickets
            child=new Tickets(childTicketPrice,childTicketSold);
            
            //calculate the total gross revenue by add the return value of getGrossRevenue() from both child and adult object
            double totalGrossRevenue=child.getRevenue().getGrossRevenue()+adult.getRevenue().getGrossRevenue();
         
          //calculate the total net revenue by add the return value of getNetRevenue() from both child and adult object
            double totalNetRevenue=child.getRevenue().getNetRevenue()+adult.getRevenue().getNetRevenue();
            
            //data to display to the user
            String result="Gross Revenue for adult ticket sold: "+ NumberFormat.getCurrencyInstance().format(adult.getRevenue().getGrossRevenue())+"\n"+
                    "Net revenue for adult tickets: "+NumberFormat.getCurrencyInstance().format(adult.getRevenue().getNetRevenue())+"\n"+
                    "Gross revenue for child tickets sold: "+NumberFormat.getCurrencyInstance().format(child.getRevenue().getGrossRevenue())+"\n"+
                    "Net revenue for child tickets: "+NumberFormat.getCurrencyInstance().format(child.getRevenue().getNetRevenue())+"\n"+
                    "Total gross revenue: "+NumberFormat.getCurrencyInstance().format(totalGrossRevenue)+"\n"+
                    "Total net revenue: "+NumberFormat.getCurrencyInstance().format(totalNetRevenue);
            
            //set the text property of resultTxtBox to result
            resultTxtBox.setText(result);
        }
        
        //program encounter error
        catch(NumberFormatException ex)
        {
            JOptionPane.showConfirmDialog(this,"An error occur. Check for invalid characters\n"
                    + "The price and amount of ticket is require for both adult and child ticket","Error",JOptionPane.CLOSED_OPTION);
        }
       
    }//GEN-LAST:event_calculateRevenueBtnMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Dimension dimension=new Dimension(this.MAXWIDTH,this.MAXHEIGHT); //new dimension object
         this.setSize(dimension); //set the size of the window 
        
         this.setMaximumSize(dimension); //set the maximium size of the window
          this.setMinimumSize(this.getSize());;//set the minimium size of the window
         this.setResizable(false); //disable window resizing
         this.setAlwaysOnTop(true); //make the window always on top
         resultTxtBox.setEditable(false);//make the control readonly
         this.setTitle("Theater Revenue"); //set the title of the window
    }//GEN-LAST:event_formWindowOpened

    private void AboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutBtnActionPerformed
        // TODO add your handling code here:
        //show message dialog displaying the purpose of the program
        JOptionPane.showMessageDialog(this,"Program calculates the net revenue, gross revenue,\n "
                + "total gross revenue and total net revenue of both adult and child ticket that was sold.\n"
                + "User must provide the amount and price of adult and child ticket sold.","About",JOptionPane.CLOSED_OPTION);
    }//GEN-LAST:event_AboutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TheaterRevenueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TheaterRevenueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TheaterRevenueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TheaterRevenueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TheaterRevenueGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutBtn;
    private javax.swing.JTextField adultTicketPriceTxtBox;
    private javax.swing.JTextField adultTicketSoldTxtBox;
    private javax.swing.JButton calculateRevenueBtn;
    private javax.swing.JTextField childTicketPriceTxtBox;
    private javax.swing.JTextField childrenTicketSoldTxtBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultTxtBox;
    // End of variables declaration//GEN-END:variables
}
